/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture, Decal } from '@react-three/drei'

export function CardModel(props: any) {
  const { nodes, materials } = useGLTF('/medias/button.glb') as any
  const texture_1 = useTexture(props.imageUrl) as any

  return (
    <group {...props} dispose={null} scale={8}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        
        {/* Base button mesh */}
        <mesh
          castShadow
          receiveShadow
          geometry={
            nodes['basic-square-round-corners-podium_basic-square-round-corner003'].geometry as any
          }
        >
          <meshPhysicalMaterial 
            color="#e6c2a8"
            transmission={1}
            opacity={1}
            transparent={true}
            roughness={0.3}
            metalness={0.2}
            thickness={1}
            ior={1.5}
          />
        </mesh>

        {/* Image container mesh */}
        <mesh
          castShadow
          receiveShadow
          position={[0, 0.025, 0.01]}
          rotation={[0, 0, Math.PI]}
          geometry={
            nodes['basic-square-round-corners-podium_basic-square-round-corner003_1'].geometry as any
          }
        >
          {/* Transparent base material */}
          <meshBasicMaterial transparent opacity={0} />
          
          {/* Decal component for the image */}
          <Decal
            position={[0, 0.02, 0]}
            rotation={[0, 0, 0]}
            scale={[0.1, 0.1, 0.1]}
          >
            <meshBasicMaterial
              map={texture_1}
              transparent={true}
              alphaTest={0.1}
              depthTest={false}
              depthWrite={false}
              polygonOffset
              polygonOffsetFactor={-4}
              side={2} // THREE.DoubleSide
            />
          </Decal>
        </mesh>

      </group>
    </group>
  )
}

useGLTF.preload('/medias/button.glb')
