/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mike (https://sketchfab.com/smirnov-mn)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/concrete-q-button-46bc2e38318843a692838e964de300cc
Title: Concrete Q button
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function KeyboardButtonModel(props: any) {
  const { nodes, materials } = useGLTF('/medias/concrete_q_button.glb') as any
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.qbut_low_m_qbut_low_0.geometry}
        scale={0.01}
      >
        <meshPhysicalMaterial
          color="#000000"
          roughness={0.8}
          metalness={0}
          transmission={1}
          opacity={0.9}
          transparent={true}
          thickness={0.1}
          ior={1.5}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/medias/concrete_q_button.glb')



